#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         0
bspc config top_padding		20
bspc config left_padding	20
bspc config window_gap          20
bspc config bottom_padding	20

bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# dunst notifications daemon
dunst &
dunst_mpdlisten &

# polybar launch
bash ~/.config/polybar/launch.sh &

# display compositing
picom &

# for network connection and bluetooth
nm-applet &
blueman-applet &
